<a href="https://colab.research.google.com/github/bard-rose/NeuromatchProject/blob/main/MATLAB_to_python_function_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###MATLAB to python function translations 

MATLAB: Interp1 
-https://uk.mathworks.com/help/matlab/ref/interp1.html
- python: scipy.interpolate interp1d
-
https://stackoverflow.com/questions/19956388/scipy-interp1d-and-matlab-interp1
-https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.interpolate.interp1d.html


In [ ]:
from scipy import interpolate
f= interpolate.interp1d(x, y, kind='linear', axis=-1, copy=True, bounds_error=True, fill_value=np.nan, assume_sorted=False)

MATLAB: [xb,yb]=stairs(x,y)
- python: can use numpy.reapeat()
-
https://stackoverflow.com/questions/42176096/how-to-create-numpy-array-of-steps-equivalent-to-matlabs-stairs-as-plotted-in

In [ ]:
import numpy 
xb = numpy.repeat(x, 2)[:-1]
yb = numpy.repeat(y, 2)[1:]

MATLAB: hist()
- python: matplotlib.pyplot.hist() 

In [ ]:
import matplotlib
matplotlib.pyplot.hist(x, bins=None, range=None, density=False, weights=None, cumulative=False, bottom=None, histtype=’bar’, align=’mid’, orientation=’vertical’, rwidth=None, log=False, color=None, label=None, stacked=False, \*, data=None, \*\*kwargs)

MATLAB: load() # for loading data 

python: 
- import pandas or can use numpy 
- or import numpy to Load data from a text file, with missing values handled as specified. https://numpy.org/doc/1.20/reference/generated/numpy.genfromtxt.html



In [ ]:
import pandas as pd
pd.read_csv('convertcsv.csv', header=None)

In [ ]:
numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, like=None)

MATLAB: rng()
- random number generator 


Python: seed(a, version)
- a : Optional. The seed value needed to generate a random number. 
- version: An integer specifying how to convert the a parameter into a integer.
Default value is 2
https://www.w3schools.com/python/ref_random_seed.asp
  

In [ ]:
import random

random.seed(10)
print(random.random())

0.5714025946899135


MATLAB: sort()

Python: 

*  list.sort() changes the list directly and doesn't return any value
*  while sorted(list) doesn't change the list and returns the sorted list.* 
*  numpy.sort() Return a sorted copy of an array.*
*  ndarray.sort Method to sort an array in-place.




In [ ]:
list = [1, 2, 4, 7, 1, 3]
sorted(list)

[1, 1, 2, 3, 4, 7]

In [ ]:
import numpy
a = [1, 2, 4, 7, 1, 3]
numpy.sort(a, axis=- 1, kind=None, order=None)

array([1, 1, 2, 3, 4, 7])

MATLAB: hold on 

Python: pyplot acts as if hold was set to True 
- plt.show()
https://stackoverflow.com/questions/21465988/python-equivalent-to-hold-on-in-matlab

MATLAB: reshape()
- matlab uses Fortran-like index order
e.g. B = reshape(A,[],2)
- forces into 2 columns 
e.g.2 c = reshape(A,[4 4 2])
ans(:,:,1)

Python: numpy.reshape(a, newshape, order='F')
- Gives a new shape to an array without changing its data.
- use F for Fortran to keen in shape with MATLAB (read the elements of a using this index order, and places the elements into the reshaped array using this Fortran index order rather than C-like order) 
-https://stackoverflow.com/questions/11892358/matlab-vs-python-reshape



In [ ]:
import numpy as np
A = np.c_[np.arange(1,17), np.arange(17,33)]
c = np.reshape(A, (4,4,2), order="F")
c[:,:,0]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

MATLAB: rand()

-Uniformly distributed random numbers

Python: numpy.random.uniform
- numpy.random.uniform(low=0.0, high=1.0, size=None)

In [ ]:
s = np.random.uniform(-1,0,10)
print(s)

[-0.72268408 -0.3445328  -0.87220825 -0.848111   -0.85285189 -0.9852942
 -0.47208215 -0.58770227 -0.81547923 -0.11976267]


MATLAB: find(X)
- returns the indices of the array X that point to nonzero elements

Python: 
- you can use numpy's nonzero function
- or numpy.where()

In [ ]:
inds = np.nonzero(A>10)
print(inds)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 11, 11, 12, 12, 13,
       13, 14, 14, 15, 15]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))


In [ ]:
 np.where(A > 10)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 11, 11, 12, 12, 13,
        13, 14, 14, 15, 15]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]))

MATLAB: diff()
- Y = diff(X) calculates differences between adjacent elements of X along the first array dimension whose size does not equal 1

Python: 
- numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
- to calculate the n-th discrete difference along the given axis.


MATLAB + python: 

-mean()

-std()
